### ISSUE TITLE
Make main view a ViewPager?

### ISSUE THREAD

**Issue by antew** [antew/RedditInPictures#56]
I was thinking the other day, what about making the main view into a ViewPager? Tapping on an image in the List/Grid views would open the image in the ViewPager.  To switch between pages you would bezel swipe.

```
  +-----------+-----------+-----------+-----------+
  |           |           |           |           |
  |           |           |           |           |
  |   Menu    | ViewPager | ListView  | GridView  |
  |           |           |           |           |
  |           |           |           |           |
  +-----------+-----------+-----------+-----------+
```

**Comment by DavidTPate** [comment]
I don't think it would be useful. Those types of features are hard to discover as it is, and throwing in some more scrolling pieces would just make it more confusing not to mention this wouldn't be good in terms of performance because of the potential amount of items that would need to be loaded. I'm just not seeing the benefits of doing this over what we have now.
